import { Service } from '@angular/core';

// TODO 4: set autoProvided: false in the @Service decorator of the service pre-generated by Angular Schematics
// and make sure to add it to the providers: [] array in the lazy feature routes file
@Service()
export class ProductService {
  // TODO 9: inject ProductApiService into the service (private, use # prefix)
  // in ProductApiService, add findByQuery(query: string) returning the HttpClient GET Observable
  // use endpoint /products with the query parameter q and response type Product[]
  // keep the Observable so switchMap can cancel an outdated request

  // TODO 5: (info) the general idea of service based state management is to have a single source of truth
  // and centralized location to manage the state of the feature (at this point, the product feature)
  // this allows us to access the same state from multiple components from unrelated parts of the application
  // (eg not direct parent child, because the component is displayed through a router-outlet, modal, dialog, ...)
  // previously implemented manual state refresh would often be in practice done with some ad-hoc
  // service based state synchronization logic, over time this logic grows and causes lot's of bugs

  // TODO 6: good thing is that with properly separated component based state management
  // we can create a new store and migrate state logic on a per component basis
  // in this exercise we're going to start with the product list component
  // the product list components contain following signal based state properties:
  //
  // query
  // loading
  // productsResource (provides loading and error state)
  // products
  //
  // queryParamsFromUrl
  // outletActivated
  // showFilter
  //
  // the second group are component specific state properties, we're going to leave them as is
  // the query, loading and products state will move into this service
  // the resource will be replaced by the rxMethod loading pipeline
  // loadingSkeleton and error will be exposed by the service for the template

  // private state

  // TODO 7: define private #query, #loading, #error and #products signals
  // initialize query to '', loading to false, error to string | undefined with undefined,
  // and products to Product[] with []
  // define #loadingSkeleton as a computed: loading is true and products is empty
  // use # JavaScript privacy so callers cannot write to the state directly

  // public state
  // TODO 8: expose the private writable signals as public signals using .asReadonly()
  // use the corresponding names without the # prefix
  // expose loadingSkeleton by referencing the private computed, which is already readonly

  // effects
  // TODO 11: let's use our freshly defined "loadByQuery" method to reload products
  // whenever the query changes using the signals effect method
  // the effect runs once initially, which takes care of our initial load
  // read #query inside the effect, then call loadByQuery(query) inside untracked
  // this tracks query changes without tracking incidental reads in the loading pipeline


  // state change methods
  // TODO 16: let's define a method to update the #query called "updateQuery"
  // the explicit methods represent only way how to update the state of the service
  // this is preferable to exposing the signals directly, because it allows us to
  // add additional logic (eg. validation, side effects, ...) to the state change

  // async methods
  // TODO 10: define loadByQuery with rxMethod<string> from @ngrx/signals/rxjs-interop
  // the component currently uses httpResource, which cancels outdated read requests
  // implement the same behavior in the service with an RxJS pipeline using switchMap
  // pass an arrow function receiving the query Observable, and return query$.pipe(...)
  // inside switchMap, set #loading to true, clear #error and return #productApiService.findByQuery(query)
  // handle that request with tapResponse from @ngrx/operators:
  // next: write the response into #products
  // error: write the HttpErrorResponse message, or a generic message for an unknown error
  // finalize: set #loading to false on completion, error or cancellation
  // handle errors inside switchMap so later searches and refreshes still work
  // retain the previous products while loading; #loadingSkeleton derives whether to show placeholders

  // TODO 20: add an async remove(productId: string) method
  // set #loading to true and clear #error; the template disables removal while loading
  // await #productApiService.remove(productId), which already returns a Promise
  // on success, call loadByQuery with the current #query value
  // keep loading true until that reload finishes; its pipeline clears loading
  // on failure, set #error and clear #loading because no reload will run
}
