import { Injectable } from '@angular/core';


// TODO 4: remove the providedIn property in the service pre-generated by Angular Schematics
@Injectable({
  providedIn: 'root'
})
export class ProductService {

  constructor() { }
}
